[package]
name = "model"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[features]
testing = [
    "common/testing",
    "database/testing",
    "errors/testing",
    "keybroker/testing",
    "metrics/testing",
    "migrations_model/testing",
    "proptest",
    "proptest-derive",
    "proptest-http",
    "runtime/testing",
    "search/testing",
    "storage/testing",
    "usage_tracking/testing",
    "value/testing",
]

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
async_lru = { path = "../async_lru" }
async_zip_0_0_9 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
cmd_util = { path = "../cmd_util" }
common = { path = "../common" }
convex_fivetran_destination = { path = "../fivetran_destination" }
convex_macro = { path = "../convex_macro" }
database = { path = "../database" }
derive_more = { workspace = true }
errors = { path = "../errors" }
fastrace = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
humansize = { workspace = true }
keybroker = { path = "../keybroker" }
maplit = { workspace = true }
metrics = { path = "../metrics" }
migrations_model = { path = "../migrations_model" }
openidconnect = { workspace = true }
pb = { path = "../pb" }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
proptest-http = { workspace = true, optional = true }
rand = { workspace = true }
reqwest = { workspace = true }
runtime = { path = "../runtime" }
saffron = { workspace = true }
search = { path = "../search" }
semver = { workspace = true }
sentry = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
storage = { path = "../storage" }
strum = { workspace = true }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
usage_tracking = { path = "../usage_tracking" }
value = { path = "../value" }

[dev-dependencies]
common = { path = "../common", features = ["testing"] }
database = { path = "../database", features = ["testing"] }
errors = { path = "../errors", features = ["testing"] }
keybroker = { path = "../keybroker", features = ["testing"] }
metrics = { path = "../metrics", features = ["testing"] }
migrations_model = { path = "../migrations_model", features = ["testing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
proptest-http = { workspace = true }
runtime = { path = "../runtime", features = ["testing"] }
search = { path = "../search", features = ["testing"] }
storage = { path = "../storage", features = ["testing"] }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types", features = [
    "testing",
] }
tempfile = { workspace = true }
usage_tracking = { path = "../usage_tracking", features = ["testing"] }
value = { path = "../value", features = ["testing"] }

[lints]
workspace = true
